# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('desc', models.CharField(max_length=254)),
                ('visible', models.BooleanField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
